Consistent theme colors
SWENT-GRP5/SOLVIT pull request #287
Opened 2024-11-08 07:28 UTC by achillet3

# Purpose:
This pull request introduces the use of Material Theme's color scheme throughout the app for both Light and Dark modes.

- **What issue does it solve?** This PR resolves the lack of consistency in colors and the overall UI throughout the app
- **What functionality does it add?** With the introduction of the Material Theme, any developer can now easily code with the correct colors while checking compatibility with Dark mode

### Related Issues:
- #261 

# Changes Made:
- Set Colors.kt to establish a theme with respect to our main colors (Green and Blue)
- Set Theme.kt to use these colors and adapt whether the app uses Light or Dark mode
- Set the Provider Profile screen to match better the Figma colors
- [Fixed signUp_emailAndPasswordInput test](https://github.com/SWENT-GRP5/SOLVIT/pull/287/commits/e3138b81703610d1dce468cbdd89cf22f9d63be3)
- Improved the Provider Info tab selected indicator
- Introduced tests for `Color.kt` and `Theme.kt`
- Improved UI of `SelectedProvider.kt` to fit the Figma better by adding shadows and modifying padding

# How to Test:
1. Run the app on phone or emulator
2. Navigate through all screens.
3. Check that UI is clear and has enough contrast in both Light and Dark conditions

<details>
<summary>Visual Helpers</summary>

##### Light Theme
1. Seeker
!(https://github.com/user-attachments/assets/1d60c7fd-b9bf-48e9-98af-8042d4f96c6a)

2. Provider
!(https://github.com/user-attachments/assets/196a3bfa-5c81-4866-a14e-100d28c6eb8d)

##### Dark Theme
1. Seeker
!(https://github.com/user-attachments/assets/1898231f-89db-4b23-9583-507d99ca418f)

2. Provider
!(https://github.com/user-attachments/assets/8367c8e0-1537-482a-8d00-40ed51561401)

</details>

# Comments:
- `ProviderCalendarScreen.kt` and `SeekerProfile.kt` are addressed in another PR (both are Theme resilient but not optimally implemented to not lose too much time and make this PR as clear as possible 

---

# Checklist:
- [x] Code adheres to project coding standards.
- [x] New and updated tests have been written and verified.
- [x] Functionality has been manually tested.
- [x] Code is free of known issues.
- [x] Documentation has been updated where applicable.

2024-11-13 10:10 UTC, yshdb5 reviewed
### Overall Comment
This PR makes valuable updates to the app’s UI by aligning various components with Material Theme’s `colorScheme`. These changes improve the consistency and adaptability of the app’s interface by replacing hardcoded colors with theme-based ones. This approach adds flexibility and makes the UI much easier to manage across different themes.

### Strong Elements
- **Theme Consistency:** Using `colorScheme` consistently across components is a great move for maintaining a unified look and feel. It simplifies color management and ensures that the UI will adapt smoothly to theme changes.
- **Code Quality:** The updates are clean and keep the original readability intact. Replacing hardcoded colors with theme references results in a cleaner, more maintainable codebase.
- **Comprehensive Application:** This PR covers a broad range of components, ensuring theme consistency is applied across the app. This thorough approach helps avoid inconsistencies in the UI.

### Areas for Improvement
- **Testing:** After these updates, it’s essential to test each UI component to confirm that the theme adjustments don’t introduce any visual inconsistencies or unexpected issues.

### Conclusion
This PR is a strong step forward for maintaining a cohesive and adaptable UI. Leveraging `colorScheme` throughout the app improves the scalability and robustness of the app’s visual style.
 Nice work!

2024-11-13 10:10 UTC, yshdb5 commented on app/src/main/java/com/android/solvit/seeker/ui/profile/SeekerProfile.kt
You said that this screen will be addressed in another PR by why were not all the colors modified to ensure compatibility with theme change?

2024-11-13 10:10 UTC, yshdb5 commented on app/src/main/java/com/android/solvit/seeker/ui/profile/EditSeekerProfile.kt
Same comment as for the `SeekerProfile.kt` file.

2024-11-13 10:10 UTC, yshdb5 commented on app/src/main/java/com/android/solvit/seeker/ui/provider/ProviderInfo.kt
The modifications in this screen should be revisited because they break the overall UI appearance, both in light mode and in dark mode.

2024-11-13 10:10 UTC, yshdb5 commented on app/src/main/java/com/android/solvit/seeker/ui/request/RequestComposables.kt
Some of the fields (title, service type, description, and deadline) have different border colors than the others (address and image upload)

2024-11-13 10:17 UTC, achillet3 commented on app/src/main/java/com/android/solvit/provider/ui/request/ListRequestsFeed.kt
As you wish, I thought there were a little bit too many different colors upon arriving on this screen. Will update back to orange with a constant :+1:

2024-11-13 10:34 UTC, achillet3 commented on app/src/main/java/com/android/solvit/seeker/ui/profile/SeekerProfile.kt
I tried to focus on changing the current color implementation. So that this PR would be easier to review. I also have the changes to SeekerProfile.kt, but I thought I would include them in another PR since they introduce quite a bit of change in these screens. But I can include these changes here

2024-11-13 10:54 UTC, achillet3 commented on app/src/main/java/com/android/solvit/seeker/ui/profile/SeekerProfile.kt
I have edited the files to make both of them Theme compliant

2024-11-13 11:02 UTC, achillet3 commented on app/src/main/java/com/android/solvit/seeker/ui/request/RequestComposables.kt
Nice catch! Fixed ✅

2024-11-13 11:38 UTC, achillet3 commented on app/src/main/java/com/android/solvit/seeker/ui/provider/ProviderInfo.kt
You're right! My bad for the mistake. It should be fixed now

2024-11-13 11:41 UTC, hjamaly commented on app/src/androidTest/java/com/android/solvit/shared/ui/authentication/SignUpTest.kt
+1

2024-11-13 11:45 UTC, hjamaly commented on app/src/main/java/com/android/solvit/provider/ui/calendar/ProviderCalendarScreen.kt
Colors are well included 👍 in this screen

2024-11-13 13:12 UTC, yshdb5 approved these changes
Great job! All the modifications were implemented, approved!

2024-11-13 18:51 UTC, hjamaly requested changes
This PR does an excellent job implementing Material Theme’s color scheme across the app, bringing a unified look and feel to both Light and Dark modes. These changes not only improve UI consistency but also simplify the development process by reducing reliance on hardcoded colors.

**Strengths**

Theme Consistency: This consistency will help maintain a smooth user experience across different screens.
Code Structure: The centralized theme management through Colors.kt and Theme.kt is well-organized, making the codebase easier to maintain and modify as needed. 

**Issues Noted**

Provider List Screen: the Provider List screen could use some adjustments to fully integrate the new theme.I’ve left a comment highlighting this area !

**Conclusion**
This PR makes a significant contribution to the app’s overall UI by standardizing colors and enhancing adaptability. Some changes are necessary but Impressive work!

2024-11-13 18:51 UTC, hjamaly commented on app/src/main/java/com/android/solvit/provider/ui/request/ListRequestsFeed.kt
N.B : I understand. This design has recently changed. Don't take account of this comment !

2024-11-14 08:00 UTC, achillet3 commented on app/src/main/java/com/android/solvit/seeker/ui/provider/SelectProvider.kt
Thanks for the feedback. I've now updated the screens so that information should be displayed correctly.
Here is the updated view of the general `selectedProvider.kt`:
![Screenshot_20241114_085700](https://github.com/user-attachments/assets/60d6d315-f7f1-4555-906e-990506df6489)
The updated location `botttomModalSheet()`:
![Screenshot_20241114_085727](https://github.com/user-attachments/assets/2295525e-b5a0-4e4e-9c44-72032406a55c)
The updated filter `botttomModalSheet()` to match the location sheet and be more consistent with the rest of the UI:
![Screenshot_20241114_085749](https://github.com/user-attachments/assets/aa532e16-1958-4e84-91b5-2eab7a245efe)

2024-11-14 08:21 UTC, hjamaly commented on app/src/main/java/com/android/solvit/seeker/ui/provider/SelectProvider.kt
Perfect ! Great Job !

2024-11-14 08:22 UTC, hjamaly approved these changes
LGTM ! All changes were made ! Excellent Job

2024-11-14 08:49 UTC, merged